Update for libvips v8.14.2 and bindgen 0.64.0
olxgroup-oss/libvips-rust-bindings pull request #35
Opened 2023-03-31 17:01 UTC by negezor

The libvips library has moved to the new meson + ninja builder. I couldn't wait for crate to update myself, so I thought I'd suggest a PR. Let me know if there are any issues with this PR here.

2023-08-27 10:22 UTC, yaa110 commented
@augustocdias could you please review and merge it?

2023-08-27 15:05 UTC, negezor commented
I also upgraded num-derive to 0.4 to go to syn 2. Now the minimum MSVR is 1.56.

2023-08-28 07:40 UTC, augustocdias commented
looks good to me but I'm not part of the organisation anymore. I can't approve/merge PRs.

I don't know if you want to tackle this, but a mistake I did was pushing the generated bidings from bindgen to github instead of always generating on build time. This will cause issues on different platforms as types has different types in each. If you're running on docker or linux (and probably mac as well) this should be fine, but on windows this will certainly fail.

2023-08-28 13:49 UTC, yaa110 commented
@negezor would you mind creating a new repo for libvips and publishing it to crates.io (e.g. as vips)?

2023-10-31 09:57 UTC, GamerBene19 commented
@augustocdias Do you still have contact to someone from the olxgroup-oss organization? It would be nice if this repository could still be maintained (by the community). Perhaps someone could be given the necessary access rights to this repository.

Otherwise I think a fork (and republishing) is necessary. It looks like [vips](https://crates.io/crates/vips) name is already taken so one would have to find a new one

2023-11-01 12:09 UTC, bassco requested changes
Once again thanks for the PR. Looks good. Just the small item to take care of and then it can be merged and published.

Apologies for the slow response.

2023-11-01 12:09 UTC, bassco commented on generator/Dockerfile
>  RUN apk add --update --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/v3.17/main \
@negezor - thanks for the work you have done with the PR.

> RUN apk add --update --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/v3.17/main \

Can you bump this to *3.18* to match the `FROM`

2023-11-02 02:12 UTC, negezor commented
@bassco Look like that's it. Perhaps I'll come back later, as libvips version 8.15.0 is just around the corner 😄

2023-11-02 07:08 UTC, merged

2023-11-02 07:11 UTC, bassco commented
@negezor - I'll publish the crate in the next few hours once I get onto the work machine

cc @BogdanVidrean